#!/bin/sh

service rsyslog reload > /dev/null 2>&1 ||:

if [ ! -d /opt/platform_server/sessions ]; then mkdir -p /opt/platform_server/sessions; fi
if [ ! -d /Android ]; then mkdir /Android; fi
if [ ! -d /opt/Android ]; then mkdir /opt/Android; chown 1000.1000 /opt/Android; fi

systemctl enable platform_server
systemctl restart platform_server

